name: run test file

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: install valgrind
      run: apt-get install valgrind -y
    - name: test
      run: make test
    - name: show files
      run: cat test/out.txt test/valgrind.txt
    - name: check for leaks
      run: cat test/valgrind.txt | grep "no leaks are possible" >/dev/null
      # grep returns 1 if no match, 0 if match
